### ISSUE TITLE
[BUG] Scheduled wallpaper change not working

### ISSUE THREAD

**Issue by iamDyeus** [iamDyeus/suppap#1]
## Description:
The application successfully downloads wallpapers and sets the initial wallpaper, but the scheduled task fails to change the wallpaper at the specified intervals.

## Steps to reproduce:
1. Install and run the application on Windows 11
2. Observe that the initial wallpaper is set correctly
3. Wait for the scheduled interval
4. Observe that the wallpaper does not change automatically

## Expected behavior:
The wallpaper should change automatically at the specified intervals.

## Actual behavior:
The wallpaper remains unchanged after the initial setup. A terminal opens for a split second after every interval time but closes & nothing happens.

## Additional information:
- Operating System: Windows 11
- Python version: 3.12.x

## Possible causes to investigate:
- Task Scheduler configuration
- Permissions issues
- Script execution in the scheduled task

**Comment by kavyachouhan** [comment]
i would like to work on this issue. Thank you

**Comment by iamDyeus** [comment]
> i would like to work on this issue. Thank you

Okay, you're good to go. Please test thoroughly before opening a PR. 
(Tip: In `config.py`, keep `WALLPAPER_CHANGE_INTERVAL` set to ≥120 seconds for an easier workaround)

**Comment by RishiAnand108** [comment]
I WOULD LIKE TO WORK ON THESE PROJECT
