### ISSUE TITLE
[FEATURE] User-Triggered Prank

### ISSUE THREAD

**Issue by Rishitshivam** [iamDyeus/suppap#13]
### Feature Description

Allows users to set a hotkey to change the wallpaper immediately.

### Problem and Solution

This feature will enable users to prank their friends on demand and possibly guess the subreddit from which the wallpaper is sourced. ;)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Rishitshivam** [comment]
I'll love to work on this feature under hacktoberfest. Please assign it to me!

**Comment by iamDyeus** [comment]
In #14, there’s a command implemented as `python main.py --change-now`
Isn’t it doing the same thing, or is your solution for a different use case?

**Comment by iamDyeus** [comment]
@Rishitshivam ?

**Comment by Rishitshivam** [comment]
yeah just saw it, sorry
