### ISSUE TITLE
Improvements in `README.md`

### ISSUE THREAD

**Issue by iamDyeus** [iamDyeus/suppap#3]
For Inspiration:
- https://github.com/iamDyeus/tkreload
- https://github.com/MananTank/radioactive-state#readme
- https://github.com/DenverCoder1/readme-typing-svg

Consider incorporating elements like start-history to enhance interactivity in your README. Creativity is encouraged!

**Comment by Blacksujit** [comment]
check PR ---> #5

**Comment by pchy-ynda** [comment]
> @KaroK365, the changes in #5 are done, but I'll keep this issue open until tomorrow. Feel free to suggest/implement any improvements! 😄

Hello! I'd like to work on this task as well to just implement a minor change to the doc. Will you assign it to me or do I have to open a PR?

**Comment by kartik-212004** [comment]
I would like to take this issue, Please

**Comment by iamDyeus** [comment]
Hey @pchy-ynda and @kartik-212004, I’m closing this issue. You can directly open a PR with a detailed description of the changes you made to the documentation.
