### ISSUE TITLE
Filter Images by Minimum Rating

### ISSUE THREAD

**Issue by KANDUKURIsaikrishna** [iamDyeus/suppap#7]
### Feature Description

Description: Implement a feature to filter images based on a minimum score from Reddit. Users can set a minimum threshold (e.g., 100) for image scores, ensuring only popular images appear as wallpapers. Update config.py to allow customization of this minimum score.

Add MIN_SCORE setting in config.py.
Modify main.py to check the Reddit post score and filter images accordingly.
Acceptance Criteria:

Only images meeting or exceeding MIN_SCORE appear as wallpapers.

### Problem and Solution

Add MIN_SCORE setting in config.py.
Modify main.py to check the Reddit post score and filter images accordingly.
Acceptance Criteria:

Only images meeting or exceeding MIN_SCORE appear as wallpapers.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by KANDUKURIsaikrishna** [comment]
I would like to work on it as part of Hacktoberfest. Can you please assign it to me.

**Comment by iamDyeus** [comment]
Great! Feel free to start working on this 😄
