### ISSUE TITLE
 User Interface for Setting Intervals

### ISSUE THREAD

**Issue by KANDUKURIsaikrishna** [iamDyeus/suppap#8]
### Feature Description

Develop a GUI using Tkinter to enable users to input and save custom intervals for each subreddit. The UI will capture intervals and save them to custom_intervals.py for use in the main script.

### Problem and Solution

Build a Tkinter UI with fields for subreddit names and intervals.
Implement save and apply functionality to store intervals in custom_intervals.py.
Update main.py to import intervals from custom_intervals.py.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by KANDUKURIsaikrishna** [comment]
I would like to work on it as part of Hacktoberfest. Can you please assign it to me.

**Comment by iamDyeus** [comment]
The idea of creating a user interface for managing configs is great. However, given the project's current scope, it might be best to stick with the CLI approach for now. A similar effort is underway in #6; if you'd like to co-author, you could reach out to the assignee about it.
